Vagrant.configure(2) do |config|
  config.vm.define "<%= host.hostname %>" do |host_config|
    host_config.vm.box = "<%= box_types[host.box_type.to_sym][:box_id] %>"
    host_config.vm.network "private_network", ip: "<%= host.ip_address %>", virtualbox__intnet: true

    host_config.vm.provider "virtualbox" do |vb|
      vb.memory = "<%= box_sizes[host.box_size.to_sym][:memory_in_mb] %>".to_i
      vb.gui = "<%= box_types[host.box_type.to_sym][:is_gui] %>" == "true"
    end

    host_config.vm.synced_folder "<%= cache_dir %>/cache/apt", "/var/cache/apt/archives", create: true
    host_config.vm.provision "shell" do |s|
      s.path = "<%= scripts_path %>/setup-hostname.sh"
      s.args = ["<%= host.hostname %>"]
    end

    if "<%= host.is_control %>" == "true"
      host_config.vm.provision "shell", path: "<%= scripts_path %>/setup-control-ssh.sh"
      host_config.vm.provision "shell", path: "<%= scripts_path %>/install-ansible.sh"
      host_config.vm.provision "shell", path: "<%= scripts_path %>/post-install-ansible.sh"
    end

    host_config.vm.provision "shell", path: "<%= scripts_path %>/setup-drone-ssh.sh"
    host_config.vm.provision "shell", path: "<%= scripts_path %>/update-system-hosts.sh"
  end
end
